# Generated by Django 4.1.4 on 2023-02-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
