# Generated by Django 4.1.4 on 2023-02-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_alter_broadcast_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
